runtime: python39  # or python38, python310 (choose a supported version)
env: standard  # "standard" is the free tier (F1 instance)
entrypoint: gunicorn -b :$PORT your_project.wsgi:application  # Replace "your_project" with your Django project name

instance_class: F1  # Free tier instance

handlers:
  # Serve static files (if using Google's static file handling)
  - url: /static
    static_dir: static/

  # Serve media files (if needed)
  - url: /media
    static_dir: media/

  # All other requests go to Django
  - url: /.*
    script: auto

# If using Cloud SQL (PostgreSQL), add this (requires billing)
# beta_settings:
#   cloud_sql_instances: "YOUR_PROJECT_ID:REGION:INSTANCE_NAME"